version: "3"

services:

  elasticsearch:
    image: elasticsearch:7.6
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk

  kibana:
    image: kibana:7.6
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - docker_elk
  
networks:
  docker_elk:
